name: build-and-deploy

on:
    push:
        branches:
            - master

jobs:
  build-and-deploy:
    name: Build & Deploy

    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Google Cloud Platform's SDK
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.gcp_project_id }}
          service_account_key: ${{ secrets.gcp_credentials }}
          export_default_credentials: true

      # Deploy to certs.gpolek.com
      - name: Deploy certs.gpolek.com
        run: gsutil -m rsync -d -c -r ./public gs://certs.gpolek.com

      #- run: gsutil iam ch allUsers:objectViewer gs://certs.gpolek.com
      #- run: gsutil web set -m index.html -e 404.html gs://certs.gpolek.com